# Generated by Django 2.1 on 2019-01-18 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Health', 'Health'), ('Personal', 'Personal'), ('Emergency', 'Emergency'), ('Entertainment', 'Entertainment'), ('Transportation', 'Transportation'), ('Others', 'Others')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=9, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True)),
                ('income', models.IntegerField(null=True)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('savings', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('automated', models.BooleanField(default=False)),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('accuracy', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('label', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('budget', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.Budget')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='expense',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='api.Goal'),
        ),
        migrations.AddField(
            model_name='budget',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='api.Profile'),
        ),
    ]
