# Generated by Django 2.1 on 2018-12-16 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181213_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='label',
        ),
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='automated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
