# Generated by Django 2.1 on 2018-12-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181216_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='automated',
            field=models.BooleanField(default=False),
        ),
    ]
