# Generated by Django 2.1 on 2018-12-19 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181216_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accuracy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
